// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApAbluPj73nP7djzTw7Mv1ZHhwQErVDwI',
    appId: '1:821601793959:web:7e215ccb77fdf5ec59e882',
    messagingSenderId: '821601793959',
    projectId: 'home-improvement-ver-2',
    authDomain: 'home-improvement-ver-2.firebaseapp.com',
    databaseURL: 'https://home-improvement-ver-2-default-rtdb.firebaseio.com',
    storageBucket: 'home-improvement-ver-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDui2zhxDBxn8rnL_eok7ufcEeZMznUaYM',
    appId: '1:821601793959:android:393d0d4c74c0be9759e882',
    messagingSenderId: '821601793959',
    projectId: 'home-improvement-ver-2',
    databaseURL: 'https://home-improvement-ver-2-default-rtdb.firebaseio.com',
    storageBucket: 'home-improvement-ver-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbi6D_d-fpXiBrzyY0A2TfxQj7e3wLCus',
    appId: '1:821601793959:ios:e7f92e662b1737cd59e882',
    messagingSenderId: '821601793959',
    projectId: 'home-improvement-ver-2',
    databaseURL: 'https://home-improvement-ver-2-default-rtdb.firebaseio.com',
    storageBucket: 'home-improvement-ver-2.appspot.com',
    iosClientId: '821601793959-lve6tbgciuamjpnrp6qk76vvp0rdn0o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeImprovement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbi6D_d-fpXiBrzyY0A2TfxQj7e3wLCus',
    appId: '1:821601793959:ios:e7f92e662b1737cd59e882',
    messagingSenderId: '821601793959',
    projectId: 'home-improvement-ver-2',
    databaseURL: 'https://home-improvement-ver-2-default-rtdb.firebaseio.com',
    storageBucket: 'home-improvement-ver-2.appspot.com',
    iosClientId: '821601793959-lve6tbgciuamjpnrp6qk76vvp0rdn0o0.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeImprovement',
  );
}
